import type { ChatMessage } from "../types";

const GEMINI_MODEL = "gemini-2.0-flash";
const GEMINI_ENDPOINT = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;
export const API_KEY_STORAGE_KEY = "arenaiq_gemini_api_key";

export function getStoredApiKey(): string {
  try {
    return localStorage.getItem(API_KEY_STORAGE_KEY) ?? "";
  } catch {
    return "";
  }
}

export function storeApiKey(key: string): void {
  try {
    if (key.trim()) {
      localStorage.setItem(API_KEY_STORAGE_KEY, key.trim());
    } else {
      localStorage.removeItem(API_KEY_STORAGE_KEY);
    }
  } catch {
    // Ignore storage errors (e.g. private browsing) - key simply won't persist.
  }
}

export interface GeminiCallResult {
  text: string;
  source: "gemini" | "offline";
}

const SYSTEM_PROMPT = `You are ArenaIQ, an on-site AI Operations Assistant embedded in a Smart Stadium Command Center.
You help control-room staff, stewards, security leads and event managers make fast, safe, and practical decisions during a live tournament fixture.
You are given a live operational context snapshot (gates, crowd density, weather, incidents, staff, concessions) and a rule-based recommendation list generated by the venue's decision engine.
Rules:
- Ground every answer in the provided context data. Reference concrete numbers (queue lengths, density %, wait times) when relevant.
- Be concise, operational, and action-oriented - like a professional operations briefing, not generic chit-chat.
- If the user asks something unrelated to stadium operations, gently redirect them back to operational matters.
- Never invent incidents, staff names, or numbers that are not present in the context.
- When there is genuine risk (critical/urgent items), lead with that first.
- Keep responses under 140 words unless the user explicitly asks for a detailed breakdown.`;

/**
 * Calls Google's Gemini generateContent REST API directly from the browser using a
 * user-supplied API key (stored only in localStorage, never hardcoded or transmitted
 * anywhere besides Google's endpoint). Falls back gracefully if no key is configured
 * or the request fails, so the assistant remains fully usable offline.
 */
export async function callGemini(
  apiKey: string,
  contextSummary: string,
  history: ChatMessage[],
  userMessage: string
): Promise<GeminiCallResult> {
  const recentHistory = history
    .slice(-6)
    .filter((m) => m.role !== "system")
    .map((m) => ({
      role: m.role === "assistant" ? "model" : "user",
      parts: [{ text: m.content }],
    }));

  const body = {
    contents: [
      ...recentHistory,
      {
        role: "user",
        parts: [
          {
            text: `LIVE OPERATIONAL CONTEXT:\n${contextSummary}\n\nSTAFF QUESTION: ${userMessage}`,
          },
        ],
      },
    ],
    systemInstruction: {
      parts: [{ text: SYSTEM_PROMPT }],
    },
    generationConfig: {
      temperature: 0.4,
      maxOutputTokens: 400,
    },
  };

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 20000);

  try {
    const res = await fetch(`${GEMINI_ENDPOINT}?key=${encodeURIComponent(apiKey)}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      signal: controller.signal,
    });

    if (!res.ok) {
      const errText = await res.text().catch(() => "");
      throw new Error(`Gemini API error ${res.status}: ${errText.slice(0, 200)}`);
    }

    const data = await res.json();
    const text: string | undefined = data?.candidates?.[0]?.content?.parts
      ?.map((p: { text?: string }) => p.text ?? "")
      .join("")
      .trim();

    if (!text) {
      throw new Error("Gemini returned an empty response.");
    }

    return { text, source: "gemini" };
  } finally {
    clearTimeout(timeout);
  }
}
